### ISSUE TITLE
Unable to build on MacOS Mojave

### ISSUE THREAD

**Issue by hashhar** [eulerto/wal2json#117]
Builds on MacOS Mojave fail with the following logs:

```log
USE_PGXS=1 make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -O2 -I. -I./ -I/Library/PostgreSQL/9.6/include/postgresql/server -I/Library/PostgreSQL/9.6/include/postgresql/internal -I/opt/local/20151229/include/libxml2 -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -c -o wal2json.o wal2json.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
In file included from wal2json.c:13:
In file included from /Library/PostgreSQL/9.6/include/postgresql/server/postgres.h:47:
/Library/PostgreSQL/9.6/include/postgresql/server/c.h:81:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
^~~~~~~~~
1 error generated.
make: *** [wal2json.o] Error 1
```

Command line tools are installed and the compatibility package under `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` has been installed.

**Comment by hashhar** [comment]
@svv2014 faced a similar issue in #103 . His steps didn't resolve it for me.

**Comment by eulerto** [comment]
@hashhar It seems a problem on your build environment. I don't use MacOS so I cannot help you.

**Comment by hashhar** [comment]
I'll try solving it and in case I come up with a solution I'll definitely share it here for future users.

**Comment by amitsingh-10** [comment]
I resolved it by the following procedure.

1.  Procured pg_config makefile location using `pg_config --pgxs`
2. Located CPPFLAGS in the makefile.
3. Added location for `stdio.h` (for me, it was `/usr/include`)
Before :
`override CPPFLAGS := -I. -I$(srcdir) $(CPPFLAGS)`
After :
`override CPPFLAGS := -I. -I$(srcdir) -I/usr/include $(CPPFLAGS)`

4. Run commands as in install instructions.
5. Restore the make file previous to original state to avoid any complications in future. (_Though I think the change is harmless._)

**Comment by offerrp** [comment]
Same error Mojave 10.14.6 stdio.h 
1) updated override CPPFLAGS := -I. -I$(srcdir) -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include $(CPPFLAGS)

2) "USE_PGXS=1 make " errors 
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
ld: warning: directory not found for option '-L/opt/local/Current/lib'
ld: warning: directory not found for option '-L/opt/local/20151229/lib'
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wal2json.so] Error 1

3) These were the two sdk in 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
MacOSX.sdk
MacOSX10.15.sdk -> MacOSX.sdk

Created A softlink MacOSX10.8.sdk -> MacOSX.sdk 

4) Recompile USE_PGXS=1 make 
Errors
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 
make: *** [wal2json.so] Error 1

Any suggestions - amitsingh-10 can you let me know ? looks like the build environment is the issue.
Instead of the make, is there an exe that can be used for wal2json ?

Thanks

**Comment by rodgarcialima** [comment]
@offerrp same problem here, did manage to find a solution?

**Comment by adamrdavid** [comment]
Solution for me on macOS Ventura 13.6 (`/usr/include` is no longer a default path, see [SO post](https://stackoverflow.com/questions/51761599/cannot-find-stdio-h#)):

1. Run: `sudo xcode-select --install` (go through install steps, this may take a while)
2. Possibly need to open xcode 1 time to allow it to install additional packages
3. This will ensure you have `/Library/Developer/CommandLineTools/usr/include/stdio.h`
4. Update cppflags to:
    ```
     override CPPFLAGS := -I. -I$(srcdir) -I/Library/Developer/CommandLineTools/usr/include/stdio.h $(CPPFLAGS)
    ```
5. Open new terminal and run install commands (make && make install)
