### ISSUE TITLE
Can't "include unchanged toast" be used now?

### ISSUE THREAD

**Issue by hanpeng1234** [eulerto/wal2json#132]
Can't "include unchanged toast" be used now? If I want to get all the data in the table (including long data), what should I do

**Comment by eulerto** [comment]
Issue #74 explains that it is not safe so that parameter was deprecated.

Even if you `alter table replica identity full`, the new row does not contain unchanged TOAST column. However, the old row contains all columns. If you want, you can add the value from old row to new row, if it is not available in new row (maybe I can add this option to wal2json, I'm not sure).

**Comment by dko-slapdash** [comment]
> maybe I can add this option to wal2json, I'm not sure

@eulerto This IMHO makes sense to do (or make at least an option which does this). This would save some traffic from PG to the client since wal2json would do the merging, and we'd be able to not expose old row and not pass it over network.

**Comment by marko-asplund** [comment]
Does the current wal2json versions provide any alternatives for `include-unchanged-toast`?

> ... (maybe I can add this option to wal2json, I'm not sure).

Were any changes done related to this @eulerto ? 🤔

**Comment by marko-asplund** [comment]
> Even if you alter table replica identity full, the new row does not contain unchanged TOAST column. However, the old row contains all columns. If you want, you can add the value from old row to new row, if it is not available in new row

So, with `alter table replica identity full` setting the before field will always include values for _all_ (both TOAST and non-TOAST columns as they were in the row before the database commit?

If a column's new value is `NULL` and old is non NULL, how does one distinguish between the case when an UPDATE statement actually set a TOAST column value to `NULL` and the value just being omitted due to the column being a TOAST column? 🤔
