### ISSUE TITLE
Large bigint values produce incorrect JSON

### ISSUE THREAD

**Issue by dko-slapdash** [eulerto/wal2json#143]
Hi.

E.g. the resulting JSON may have something like: `"columnvalues":[2001000009664553892,...]` and, when passed to JSON.parse(), this value is silently converted to `2001000009664554000` (notice the loss of the last 4 digits). This is because it's a bigint value greater than Number.MAX_SAFE_INTEGER.

JSON format does not support bigints btw. Even the new BigInt class in JS doesn't make any difference here, bigints are just beyond the scope of JSON by definition (and tools like https://www.npmjs.com/package/json-bigint don't make much difference since they're extremely slow in comparison to the native JSON.parse()).

I don't have a clear proposal on how to address this... maybe an option which tells wal2json to represent all bigints as a string (not as a number) would be beneficial. Or an option like `bigint-to-string-fields` which accepts a comma-separated list of bigint fields (or `*` to rule them all) for which a string will be emitted instead of a plain number...

This is a common problem of similar tools actually. E.g. Debezium's kafka-connect has the same problem too.

**Comment by eulerto** [comment]
@dko-slapdash JSON spec does not say anything about number precision. I don't see a bug here. If a JSON value doesn't parse, blame JSON library. I don't like the idea of modifying data types behind the scenes because it violates semantics. As I said in issue #144, it is not wal2json business to mangle values to fix someone else problem.
