### ISSUE TITLE
Lambda taking longer to consume replication

### ISSUE THREAD

**Issue by rajpaly** [eulerto/wal2json#198]
Hello,

I'm doing logical stream from rds postgres instance to kinesis . attached below my lambda function code and and lambda time out is set to 150 sec and and cloud-watch event trigger set for 5 mins. whenever i do some burst load (200k inserts and 50k updated in 10 minutes window) it's taking 2 hours to catch up. any suggestions to reduce the latency?
and also my current lamda extracts until it reach timeout is there any way we can avoid lambda timeouts?

`import sys
import logging
import psycopg2
import boto3
import json
import random
import calendar
import time
from datetime import datetime
from psycopg2.extras import LogicalReplicationConnection

my_stream_name = 'test'
kinesis_client = boto3.client('kinesis', region_name='us-east-1')

logger = logging.getLogger()
logger.setLevel(logging.INFO)

try:
    my_connection  = psycopg2.connect(
                     "dbname='profiles' host='myhost' user='user' password='pwd'" ,
                      connection_factory = LogicalReplicationConnection)
except:
    logger.error("ERROR: Unexpected error: Could not connect to RDS for PostgreSQL instance.")
    sys.exit()

logger.info("SUCCESS: Connection to RDS for PostgreSQL instance succeeded")

def handler(event, context):
    """
    This function streams content from RDS for PostgreSQL into Kinesis
    """

    cur = my_connection.cursor()
    cur.start_replication(slot_name = 'waljson_test_slot', options = {'pretty-print' : 1}, decode= True)

    cur.consume_stream(consume)

def consume(msg):
    kinesis_client.put_record(StreamName=my_stream_name, Data=json.dumps(msg.payload), PartitionKey="default")
    print (msg.payload)
    msg.cursor.send_feedback(flush_lsn=msg.data_start)`

**Comment by rajpaly** [comment]
@jbergknoff-rival were you able to process the wal to kinesis faster(https://github.com/psycopg/psycopg2/issues/940). i'm trying to implement similar please review my code and let me know if you see any problems

**Comment by jbergknoff** [comment]
@rajpaly nope, never found a way around that. The company where I was doing that work ceased to exist, unfortunately. One promising lead:

I set up an SSH tunnel to our RDS instance, hooked up `pg_recvlogical` running locally, and threw a bunch of activity at the database. This cut (1) our logical replication processing code, and (2) Kinesis, out of the picture. I saw a big delay pulling the data from a `wal2json` replication slot, but **not from a `test_decoding` replication slot**. The `test_decoding` slot was significantly faster. The behavior of `wal2json` also varied with vs. without chunking, but both were significantly slower than `test_decoding`.

This seems to suggest that the bottleneck is in `wal2json`, not in Postgres proper or in RDS's handling of it (we were using Aurora, for what it's worth), and also not in our code or in Kinesis. I never got around to investigating switching our consumer to use `test_decoding`, but a cursory look at the format suggested it would be adequate for our purposes. As I recall, the documentation mentions not to use `test_decoding` for anything real, but didn't give a reason (maybe format subject to change?). You might want to look in that direction.

**Comment by rajpaly** [comment]
Thank you @jbergknoff  i'm seeing similar slowness using test_decoding as well. i did run as test for 700tps for 10 minutes. with test decoding it's consuming around 700 transactions per minute. do you see any issue with my code

`def handler(event, context):
    """
    This function streams content from RDS for PostgreSQL into Kinesis
    """

    cur = my_connection.cursor()

    cur.start_replication(slot_name = 'test_slot', decode= True)

    cur.consume_stream(consume)

def consume(msg):
    kinesis_client.put_record(StreamName=my_stream_name, Data=json.dumps(msg.payload), PartitionKey="default")
    print (msg.payload)
    msg.cursor.send_feedback(flush_lsn=msg.data_start)`

**Comment by jbergknoff** [comment]
> do you see any issue with my code

Yes, the blocking writes to Kinesis are very likely a bottleneck in your code. I recommend benchmarking without that and see if it's any better.

**Comment by rajpaly** [comment]
@jbergknoff Do you mean use chunks i did try setting it in chunks as well with no to little improvement

**Comment by joekohlsdorf** [comment]
Here is what I would do:
* use asyncpg
* use async-kinesis
* use orjson
* raise memory of your Lambda, this will give you more CPU

**Comment by eulerto** [comment]
How did you insert these 200k rows? A single transaction? How did you update these 50k rows? A single transaction?

Large and long running transactions could take a considerable amount of time during logical decoding. 

During the logical decoding, Postgres needs to read WAL from the beginning of the transaction until its end. If you start a transaction at 08:00 AM, execute one INSERT one second later, execute an UPDATE at 09:00 AM and commit. From the logical decoding perspective, it should read/process the amount of WAL during the transaction run even though not all data between 08:00 and 09:00 is from your long running transaction (indeed the result will be only 2 changes).

The large transaction has a similar scenario. Due to the considerable amount of data into one single transaction, the logical decoding has to spill the changes to disk while processing your large transaction because it doesn't fit in memory. Postgres uses temporary files to write the changes while processing the transaction and read the changes to forward it to the output plugin.

In Postgres 13, there is a parameter to tweak the amount of memory to be used by logical decoding (`logical_decoding_work_mem`). In previous Postgres versions (10 - 12), there is a hardcoded number of changes (4096) from which Postgres will start writing changes to temporary files.

Your slowdown seems to be related to spill changes to disk.
