### ISSUE TITLE
Is it possible to use wal2json on arm64 architecture?

### ISSUE THREAD

**Issue by ivankovbas** [eulerto/wal2json#208]
I'm using PostgreSQL with the wal2json plugin installed into a docker container in order to set up a local environment for my project.
Here is an example of my Dockerfile:
```
FROM postgres:10.14
RUN apt update && apt install -y postgresql-10-wal2json postgresql-contrib
```

Currently, I'm trying to set up and run my project on the new MacBook on the M1 chip, but I'm getting the following error: `E: Unable to locate package postgresql-10-wal2json`.
When I build the docker image on m1 MacBook it uses the `aarch64` version of Debian OS:
```
root@8c75279c1a69:/# uname -a
Linux 8c75279c1a69 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 GNU/Linux
```
So, I believe, the problem is that there is no `aarch64`/`arm64` version of the `postgresql-10-wal2json` package in the apt repository.

Also, I've thought about compiling wal2json by myself, but the problem is that there is no `postgresql-server-dev-10` package available in the repository as well:
```
root@8c75279c1a69:/# apt-cache search postgresql-server-dev
postgresql-server-dev-9.6 - development files for PostgreSQL 9.6 server-side programming
postgresql-server-dev-all - extension build tool for multiple PostgreSQL versions
```

**Comment by eulerto** [comment]
@ivankovbas I've never tried to compile wal2json in this architecture but since there are [packages available](https://packages.debian.org/bullseye/arm64/postgresql-13-wal2json/filelist) and zero complains from packagers I think it works just fine. It seems this specific docker image does **not** support arm64. 

_poking Docker Hub..._

[postgres:10.18](https://github.com/docker-library/postgres/blob/a7a749d0ce8b8cd54c5545f6d9489d755af00659/10/stretch/Dockerfile) uses `stretch` as a base OS and it doesn't install the repository for architectures that are not [amd64, i386, and ppc64el](https://github.com/docker-library/postgres/blob/a7a749d0ce8b8cd54c5545f6d9489d755af00659/10/stretch/Dockerfile#L102) but [it builds postgres](https://github.com/docker-library/postgres/blob/a7a749d0ce8b8cd54c5545f6d9489d755af00659/10/stretch/Dockerfile#L108). So, there is not only `postgresql-10` package.

Use [postgres:10.18-buster](https://github.com/docker-library/postgres/blob/a7a749d0ce8b8cd54c5545f6d9489d755af00659/10/buster/Dockerfile) that includes [arm64](https://github.com/docker-library/postgres/blob/a7a749d0ce8b8cd54c5545f6d9489d755af00659/10/buster/Dockerfile#L102).

**Comment by ivankovbas** [comment]
It works well with `postgres:10.18-buster` image, thank you a lot)
