### ISSUE TITLE
wal2json and initial snapshot

### ISSUE THREAD

**Issue by wiwwo** [eulerto/wal2json#215]
Hi!
Any plan to implement the "transfer" of the initial snapshot?

**Comment by eulerto** [comment]
What do you mean by "transfer"? If you mean an initial sync, there is no such plan because wal2json is just the output plugin. It is not a replication or a CDC tool. Instead, it is part of an architecture that delivers changes in a certain format (JSON in this case). These changes are processed by the tool that gathers data from your database server.
