### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by rdunklau** [eulerto/wal2json#93]
Hello,

The current code incorporates several fixes (such as the deprecation of the unsafe, default to on option "include-unchanged-toast"). It would be great to publish a new release incorporating those changes, so that they can be integrated in distributions.

**Comment by davidfetter** [comment]
Bump

**Comment by igouss** [comment]
bump, I think we should release a new one. A lot of changes were made since the last release.
postgres10 https://yum.postgresql.org/10/redhat/rhel-7-x86_64/repoview/wal2json10.html 
postgres11 https://yum.postgresql.org/11/redhat/rhel-7-x86_64/repoview/wal2json11.html

I'm not sure how to contact the original author of the RPM. I think it's Devrim Gündüz. I've send him a twitter ping.

**Comment by devrimgunduz** [comment]
@eulerto ping.

**Comment by devrimgunduz** [comment]
> bump, I think we should release a new one. A lot of changes were made since the last release.
> postgres10 https://yum.postgresql.org/10/redhat/rhel-7-x86_64/repoview/wal2json10.html
> postgres11 https://yum.postgresql.org/11/redhat/rhel-7-x86_64/repoview/wal2json11.html
> 
> I'm not sure how to contact the original author of the RPM. I think it's Devrim Gündüz. I've send him a twitter ping.

We cannot roll a new RPM release until @eulerto wraps up a new tarball.

**Comment by eulerto** [comment]
New version released.

**Comment by singingwolfboy** [comment]
Thanks, @eulerto! I really appreciate all the work you've put into this. ✨
